#!/usr/bin/ksh
#    This file is part of kchain

#    kchain is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    kchain is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with kchain.  If not, see <http://www.gnu.org/licenses/>.

# (C) 2010 by Stefan Marsiske, <stefan.marsiske@gmail.com>

source ~/.kchainrc 2>/dev/null
source .kchainrc 2>/dev/null

[[ $# -lt 5 ]] && {
    print "${0##*/} <filename> <size> <keyfile> <name> <mountpoint> [<kchainroot>]"
    exit 1
}

filename="$1"
size="$2"
keyfile="$3"
name="$4"
mountpoint="$5"
kchainroot="$6/.kchain"

dd if=/dev/zero bs=1M count=$size | openssl enc -aes-128-ofb -k $RANDOM -out "$filename" || {
    print "something went wrong bailing out"
    exit 1
}
openssl rand -out "$keyfile" 8192 || {
    rm "$filename"
    print "something went wrong bailing out"
    exit 1
}
sudo /sbin/cryptsetup create -q -c aes-xts-plain64 -l 8192 -h sha512 --key-file "$keyfile" "$name" "$filename" || {
    rm "$filename" "$keyfile"
    print "something went wrong bailing out"
    exit 1
}
sudo /sbin/mkfs.ext4 "/dev/mapper/$name" || {
    rm "$filename" "$keyfile"
    sudo cryptsetup remove "$name"
    print "something went wrong bailing out"
    exit 1
}
sudo cryptsetup remove "$name"
[[ -n "$kchainroot" ]] && {
    cat >"$kchainroot/mounts/$name" <<EOF
name=$name
keyfile=$keyfile
image=$filename
mountdir=$mountpoint
EOF
    ${0%/*}/mount-images "$kchainroot/mounts/$name"
}
echo "succesfully created $kchainroot/mounts/$name"
