#!/usr/bin/ksh
#    This file is part of kchain

#    kchain is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    kchain is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with kchain.  If not, see <http://www.gnu.org/licenses/>.

# (C) 2010 by Stefan Marsiske, <stefan.marsiske@gmail.com>

source ~/.kchainrc 2>/dev/null
source .kchainrc 2>/dev/null

[[ $# -lt 5 ]] && {
    print "${0##*/} <filename> <size> <keyfile> <name> <mountpoint> [<kchainroot>]"
    exit 1
}

filename="$1"
size="$2"
keyfile="$3"
name="$4"
mountpoint="$5"
kchainroot="$6/.kchain"

dd if=/dev/zero of="$filename" bs=1M count=$size
openssl rand -out "$keyfile" 2048
sudo /sbin/cryptsetup luksFormat -q -c aes-xts-plain64 -s 512 -h sha512 "$filename" "$keyfile"
sudo /sbin/cryptsetup luksOpen "$filename" "$name" --key-file "$keyfile"
sudo /sbin/mkfs.ext4 "/dev/mapper/$name"
sudo /sbin/cryptsetup luksClose "$name"
[[ -n "$kchainroot" ]] && {
    cat >"$kchainroot/mounts/$name" <<EOF
name=$name
keyfile=$keyfile
image=$filename
mountdir=$mountpoint
EOF
    ${0%/*}/mount-images "$kchainroot/mounts/$name"
}
echo "succesfully created $kchainroot/mounts/$name"
