#!/usr/bin/ksh

# as root

[[ $# -lt 1 ]] && {
echo "${0##*/} /dev/sdxX # partition for kchain on your stick"
exit 1
}
device="$1"
name="${2:-ukey}"

/sbin/udevadm info -a -p $(/sbin/udevadm info -q path -n "${device:0:8}") |
   while read line; do
       [[ -n "$ser" && -n "$prod" && -n "$vend" ]] && break
       [[ "$line" =~ "ATTRS{idVendor}" ]] && { vend="$line"; continue; }
       [[ "$line" =~ "ATTRS{serial}" ]] && { ser="$line"; continue; }
       [[ "$line" =~ "ATTRS{idProduct}" ]] && { prod="$line"; continue; }
done

entry="KERNEL==\"sd?${1##*[a-zA-z]}\", $ser, $prod, $vend, SYMLINK+=\"$name\""
sudo sh -c "echo '$entry' >>/etc/udev/rules.d/81-kchain.rules"
