#!/usr/bin/ksh
#    This file is part of kchain

#    kchain is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    kchain is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with kchain.  If not, see <http://www.gnu.org/licenses/>.

# (C) 2012 by Stefan Marsiske, <stefan.marsiske@gmail.com>

LABEL=keys
MOUNTDIR=/media/$LABEL

source ~/.kchainrc 2>/dev/null
source .kchainrc 2>/dev/null

function umountimage {
    name=""; keyfile=""; mountdir=""; image=""
    source "$1"
    mountpoint -q "$mountdir" && SUDO_ASKPASS=/usr/bin/ssh-askpass sudo -A /bin/umount "$mountdir"
    [[ -e "/dev/mapper/$name" ]] && sudo /sbin/cryptsetup luksClose $name
    lb="$(sudo /sbin/losetup -j "$image" | cut -d: -f1)"
    [[ -n "$lb" ]] && sudo /sbin/losetup -d "$lb"
}

break=/bin/false
while [[ -f "$1" ]]; do
    break=/bin/true
    echo "umounting image $1"
    umountimage $1
    shift 1
done
$break && exit

if [ -d "$MOUNTDIR/.kchain/mounts" ]; then
    for i in `run-parts --list "$MOUNTDIR/.kchain/mounts" `; do
        umountimage "$i"
    done
fi

if [ -d "$CACHEDIR/mounts" ]; then
    for i in `run-parts --list "$CACHEDIR/mounts" `; do
        umountimage "$i"
        rm "$i"
    done
fi
